basePath: /api/v1
definitions:
  api.auth:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  v1.tagCreate:
    properties:
      name:
        example: account name
        type: string
      state:
        example: 0
        type: integer
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger API for gsgo
  version: "2.0"
paths:
  /auth:
    post:
      parameters:
      - description: 新建
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.auth'
          type: object
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: login
      tags:
      - Auth
  /tags:
    post:
      parameters:
      - description: 新建
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.tagCreate'
          type: object
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: AddTag
      tags:
      - 标签
  /tags/:
    get:
      consumes:
      - application/json
      description: get tags list
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            type: string
      summary: get tags list
      tags:
      - 标签
  /tags/{id}:
    get:
      consumes:
      - application/json
      description: get tag by ID
      operationId: tagId
      parameters:
      - description: tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: get a tag
      tags:
      - 标签
    put:
      consumes:
      - application/json
      description: get tag by ID
      operationId: tagId
      parameters:
      - description: tag ID
        in: path
        name: id
        required: true
        type: integer
      - description: 修改
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.tagCreate'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: get a tag
      tags:
      - 标签
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
